apiVersion: v1
kind: Pod
metadata:
  name: stress
  labels:
    role: stress
  annotations:
    my-scheduler/alpha: "0.9"
spec:
  schedulerName: my-scheduler
  containers:
  - name: stress
    image: polinux/stress
    args: ["--cpu", "2", "--timeout", "120s"]
    resources:
      requests:
        cpu: "500m"
        memory: "128Mi"
