apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  annotations:
    my-scheduler/alpha: "0.2"
spec:
  schedulerName: my-scheduler
  containers:
  - name: busybox
    image: busybox
    command: ["sleep", "3600"]
