apiVersion: v1
kind: Pod
metadata:
  name: server
  labels:
    role: server
spec:
  schedulerName: my-scheduler
  containers:
  - name: server
    image: python:3.9-slim
    command: ["sh", "-c"]
    args:
      - |
        pip install flask >/dev/null 2>&1 && \
        cat > app.py <<'EOF'
        from flask import Flask
        import time
        app = Flask(__name__)

        @app.route('/')
        def handle():
            start = time.time()
            while time.time() - start < 2:
                pass
            return "ok\n"

        if __name__ == "__main__":
            app.run(host="0.0.0.0", port=8080)
        EOF
        python app.py
    ports:
      - containerPort: 8080
    resources:
      requests:
        cpu: "400m"
        memory: "128Mi"
