apiVersion: v1
kind: Pod
metadata:
  name: cpu-stress
spec:
  containers:
  - name: stress
    image: progrium/stress
    args: ["--cpu", "2", "--timeout", "120s"]
    resources:
      requests:
        cpu: "500m"
      limits:
        cpu: "1"
