apiVersion: v1
kind: Pod
metadata:
  name: cpu-stress
spec:
  schedulerName: my-scheduler
  containers:
  - name: stress
    image: polinux/stress
    args: ["--vm", "1", "--vm-bytes", "512M", "--timeout", "120s"]
    resources:
      requests:
        memory: "256Mi"
      limits:
        memory: "512Mi"
